licenseKey: ZZZZZZ
region: US
interval: 60
runAsService: false
pipeline:
  receiveBufferSize: 50
  harvestInterval: 15
  instances: 3
log:
  level: warn
  fileName: trace.log
bitmovinMetricPrefix: bitmovin.
bitmovinApiKey: ZZZZZZ
bitmovinLicenseKey: ZZZZZZ
bitmovinTenantOrg: ZZZZZZ
bitmovinNullValueString: "<NULL>"
bitmovinTimeout: 30
queries:
## Default Queries
- type: max_concurrentviewers
  name: max_concurrent_viewers
- type: average
  metric: REBUFFER_PERCENTAGE
  name: avrg_rebuff_percent
- type: count
  metric: PLAY_ATTEMPTS
  name: count_play_attempts
- type: count
  metric: IMPRESSION_ID
  name: count_impression_id
  filters:
    VIDEOSTART_FAILED_REASON:
      operator: NE
      value: PAGE_CLOSED
    VIDEOSTART_FAILED:
      operator: EQ
      value: true
- type: count
  metric: VIDEO_STARTUPTIME
  name: count_video_startup_time
  filters:
    VIDEO_STARTUPTIME:
      operator: GT
      value: 0
    PAGE_LOAD_TYPE:
      operator: EQ
      value: 1
- type: average
  metric: VIDEO_BITRATE
  name: avrg_video_bitrate
  filters:
    VIDEO_BITRATE:
      operator: GT
      value: 0
- type: average
  metric: VIEWTIME
  name: avrg_view_time
  orderBy:
  - name: FUNCTION
    order: DESC
  - name: MINUTE
    order: DESC
